Acme\GuardaBundle\Entity\Categoria:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    nombre:
      type: string
      length: '50'
  lifecycleCallbacks: {  }
  oneToMany:
    productos:
        targetEntity: Producto
        mappedBy: categoria
